# Generated by Django 4.1.7 on 2023-04-12 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('brand_img', models.ImageField(blank=True, null=True, upload_to='brand')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('brand_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.brand'),
        ),
    ]
