# Generated by Django 4.1.7 on 2023-04-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_cart_coupon_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
