# Generated by Django 4.1.7 on 2023-04-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
