# Generated by Django 4.1.7 on 2023-04-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0002_coupon_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='off_percent',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='status',
        ),
    ]
