# Generated by Django 4.1.7 on 2023-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_variant', '0003_remove_coupon_expiry_date_remove_coupon_off_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='max_discount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_price',
            field=models.PositiveBigIntegerField(default=799),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_amount',
            field=models.PositiveBigIntegerField(default=15000),
        ),
    ]
