# Generated by Django 4.1.7 on 2023-04-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='uploads')),
                ('image2', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
